# Generated by Django 3.1.7 on 2021-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postdate',
            field=models.DateField(auto_now=True),
        ),
    ]
